#!/usr/bin/env bash

pub4=$(curl -4 -s https://ifconfig.me)

pub6=$(curl -6 -s https://ifconfig.me)

iface=$(ip route get 1.1.1.1 | awk '{print $5; exit}')
local4=$(ip -4 addr show "$iface" | awk '/inet / {print $2}' | cut -d/ -f1)

echo "Public IPv4:  $pub4"
echo "Public IPv6:  $pub6"
echo "Local IPv4:   $local4"

