"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_bg)\
$os\
[╱ ](fg:color_fg bg:color_bg)\
$directory\
[╱ ](fg:color_fg bg:color_bg)\
[ ](bg:color_bg)\
($status[╱ ](fg:color_fg bg:color_bg))\
($cmd_duration[╱ ](fg:color_fg bg:color_bg))\
($direnv[╱ ](fg:color_fg bg:color_bg))\
($package[╱ ](fg:color_fg bg:color_bg))\
($c[╱ ](fg:color_fg bg:color_bg))\
($cpp[╱ ](fg:color_fg bg:color_bg))\
($cmake[╱ ](fg:color_fg bg:color_bg))\
($conda[╱ ](fg:color_fg bg:color_bg))\
($container[╱ ](fg:color_fg bg:color_bg))\
($docker_context[╱ ](fg:color_fg bg:color_bg))\
($java[╱ ](fg:color_fg bg:color_bg))\
($lua[╱ ](fg:color_fg bg:color_bg))\
($nodejs[╱ ](fg:color_fg bg:color_bg))\
($python[╱ ](fg:color_fg bg:color_bg))\
($ruby[╱ ](fg:color_fg bg:color_bg))\
($rust[╱ ](fg:color_fg bg:color_bg))\
($username$hostname[╱ ](fg:color_fg bg:color_bg))\
$time\
[](fg:color_bg)
$character\
"""

add_newline = true
palette = 'dark'

[palettes.dark]
color_bg = '#5551A7'   # purple
color_fg = '#c3c3c8'   # foreground
color_ok = '#6E6BCF'
color_warn = '#837BD8'
color_high = '#CBB7F9'
color_err = '#9A8AB7'

[cmd_duration]
min_time = 3000
format = '[$duration  ]($style)'
style = 'fg:color_high bg:color_bg'

[status]
disabled = false
format = '[$symbol( $common_meaning)( $signal_name)( $signal_number)( $maybe_int) ]($style)'
style = 'bold fg:color_err bg:color_bg'
success_style = 'bold fg:color_ok bg:color_bg'
symbol = '✘'
map_symbol = false
pipestatus = true
pipestatus_format = '[$pipestatus]($style)'

[character]
success_symbol = '[❯](bold fg:color_ok)'
error_symbol = '[❯](bold fg:color_err)'
vimcmd_symbol = '[❮](bold fg:color_ok)'
vimcmd_replace_one_symbol = '[▶](bold fg:color_ok)'
vimcmd_replace_symbol = '[▶](bold fg:color_ok)'
vimcmd_visual_symbol = '[V](bold fg:color_ok)'

[time]
disabled = false
format = '[$time  ]($style)'
style = 'fg:color_ok bg:color_bg'

[fill]
symbol = '─'
style = 'fg:color_fg'

[os]
format = '[ $symbol]($style)'
style = 'fg:color_fg bg:color_bg'
disabled = false

[directory]
format ='[$read_only]($read_only_style)[ ](fg:color_high bg:color_bg)[$path ]($style)'
style = 'fg:color_warn bg:color_bg'
read_only_style = 'bold fg:color_high bg:color_bg'
repo_root_format = '[$read_only]($read_only_style)[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path ]($style)'
before_repo_root_style = 'bold fg:color_high bg:color_bg'
repo_root_style = 'bold fg:color_warn bg:color_bg'
read_only = "󰌾 "
home_symbol = '~'
truncate_to_repo = false
use_logical_path = false


[direnv]
format = '[$symbol$loaded/$allowed ]($style)'
style = 'bold fg:color_warn bg:color_bg'

[c]
format = '[$symbol($version(-$name) )]($style)'
style = 'bold fg:color_ok bg:color_bg'
symbol = " "

[cpp]
format = '[$symbol($version(-$name) )]($style)'
style = 'bold fg:color_ok bg:color_bg'
symbol = " "

[cmake]
format = '[$symbol($version )]($style)'
style = 'bold fg:color_high bg:color_bg'
symbol = " "

[conda]
format = '[$symbol$environment ]($style)'
style = 'bold fg:color_ok bg:color_bg'
symbol = " "

[container]
format = '[$symbol \[$name\] ]($style)'
style = 'bold dimmed fg:color_err bg:color_bg'

[docker_context]
format = '[$symbol$context ]($style)'
style = 'bold fg:color_high bg:color_bg'
symbol = " "

[username]
format = '[$user]($style)'
style_root = 'bold fg:color_warn bg:color_bg'
style_user = 'fg:color_high bg:color_bg'

[hostname]
format = '[$ssh_symbol$hostname]($style)'
style = 'fg:color_high bg:color_bg'
ssh_symbol = '@'

[java]
format = '[${symbol}(${version} )]($style)'
style = 'dimmed fg:color_err bg:color_bg'
symbol = " "

[lua]
format = '[$symbol($version )]($style)'
style = 'bold fg:color_high bg:color_bg'
symbol = " "

[nodejs]
format = '[$symbol($version )]($style)'
style = 'bold fg:color_err bg:color_bg'
symbol = " "

[os.symbols]
Arch = " "

[package]
format = '[$symbol$version ]($style)'
style = 'bold fg:color_err bg:color_bg'
symbol = "󰏗 "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = 'bold fg:color_warn bg:color_bg'
symbol = " "

[ruby]
format = '[$symbol($version )]($style)'
style = 'bold fg:color_err bg:color_bg'
symbol = " "

[rust]
format = '[$symbol($version )]($style)'
style = 'bold fg:color_err bg:color_bg'
symbol = "󱘗 "

