# Shell variables
# Generated by 'wal'
wallpaper="/home/malissa/wallpapers/1920x1080/Mountains/wallhaven-42kykx.jpg"

# Special
background='#0f1124'
foreground='#c3c3c8'
cursor='#c3c3c8'

# Colors
color0='#0f1124'
color1='#5551A7'
color2='#6E6BCF'
color3='#837BD8'
color4='#9A8AB7'
color5='#A099EF'
color6='#CBB7F9'
color7='#c3c3c8'
color8='#5e6074'
color9='#5551A7'
color10='#6E6BCF'
color11='#837BD8'
color12='#9A8AB7'
color13='#A099EF'
color14='#CBB7F9'
color15='#c3c3c8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
