--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/melissa/wallpapers/current.png"

-- Special
background="#180e20"
foreground="#c5c2c7"
cursor="#c5c2c7"

-- Colors
color0="#180e20"
color1="#74489C"
color2="#7953C5"
color3="#A24D9F"
color4="#9655A7"
color5="#A666D5"
color6="#CD73E4"
color7="#c5c2c7"
color8="#675d72"
color9="#74489C"
color10="#7953C5"
color11="#A24D9F"
color12="#9655A7"
color13="#A666D5"
color14="#CD73E4"
color15="#c5c2c7"
