--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/malissa/wallpapers/1920x1080/Mountains/wallhaven-42kykx.jpg"

-- Special
background="#0f1124"
foreground="#c3c3c8"
cursor="#c3c3c8"

-- Colors
color0="#0f1124"
color1="#5551A7"
color2="#6E6BCF"
color3="#837BD8"
color4="#9A8AB7"
color5="#A099EF"
color6="#CBB7F9"
color7="#c3c3c8"
color8="#5e6074"
color9="#5551A7"
color10="#6E6BCF"
color11="#837BD8"
color12="#9A8AB7"
color13="#A099EF"
color14="#CBB7F9"
color15="#c3c3c8"
