#!/usr/bin/env bash
output_base="~/Pictures/Screenshots"
year=$(date +'%Y')
month=$(date +'%B')
timestamp=$(date +'%d-%H-%M-%S')
random=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 6)
filename="$year/$month/${timestamp}-${random}.png"

mkdir -p "$output_base/$year/$month"
hyprshot -f "$filename" -m region -o "$output_base"
